### ISSUE TITLE
cultionet train CUDA error

### ISSUE THREAD

**Issue by mmann1123** [jgrss/cultionet#67]
@jgrss  This almost certainly has to do with my aws build constraints. 

```
cultionet train --project-path . \
                --val-frac 0.2 \
                --random-seed 500 \
                --batch-size 4 \
                --epochs 30 \
                --filters 32 \
                --device gpu \
                --patience 5 \
                --learning-rate 0.001 \
                --reset-model
```
getting the following error:
```
Global seed set to 500
Processing...
Done!
Global seed set to 500
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch_backup_april_11/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/pytorch_backup_april_11/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 1405, in main
    train_model(args)
  File "/opt/conda/envs/pytorch_backup_april_11/lib/python3.9/site-packages/cultionet/scripts/cultionet.py", line 1245, in train_model
    class_counts = data_values.crop_counts.to("cuda")
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

```
nvidia-smi
Failed to initialize NVML: Driver/library version mismatch
````
```
cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  470.161.03  Wed Oct 19 00:10:36 UTC 2022
GCC version:  gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
```

99% sure I have the wrong driver installed.... by default the deep learning instances in AWS currently have 
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0 `

**Comment by mmann1123** [comment]
Ok a bit more progress but could use your help here. I build an instance from your docker file but on aws. @jgrss 

I am getting the following error when training:

```
root@ac87ad3a7366:/home/field_bounds# cultionet train --project-path . \
>                 --val-frac 0.2 \
>                 --random-seed 500 \
>                 --batch-size 4 \
>                 --epochs 30 \
>                 --filters 32 \
>                 --device gpu \
>                 --patience 5 \
>                 --learning-rate 0.001 \
>                 --reset-model
Global seed set to 500
Processing...
Done!
Global seed set to 500
Calculating means: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:00<00:00, 79.49it/s]
Calculating SSEs: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:00<00:00, 81.94it/s]
Processing...
Done!
Global seed set to 500
Traceback (most recent call last):
  File "/root/.local/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1398, in main
    train_model(args)
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1243, in train_model
    cultionet.fit(
  File "/root/.local/lib/python3.8/site-packages/cultionet/model.py", line 401, in fit
    trainer = pl.Trainer(
  File "/root/.local/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'auto_lr_find'
```

I am seeing you removed it but not sure what to use instead. Thoughts?

**Comment by jgrss** [comment]
Hmm, which version of `pytorch_lightning` do you have installed?

**Comment by mmann1123** [comment]
```
torch                    2.0.0
torch-cluster            1.6.1
torch-geometric          2.3.0
torch-scatter            2.1.1
torch-sparse             0.6.17
torch-spline-conv        1.2.2
torchaudio               2.0.1
torchmetrics             0.10.3
torchvision              0.15.1
tornado                  6.1
```
@jgrss

**Comment by jgrss** [comment]
Thanks -- also, how about `pytorch_lightning`?
```commandline
python -c "import pytorch_lightning as pl;print(pl.__version__)"
```

**Comment by mmann1123** [comment]
2.0.1.post0

**Comment by mmann1123** [comment]
Seeing this on the changelog of pytorch lightning:
`Removed `Trainer(auto_lr_find=...)` in favor of `Tuner(trainer).lr_find()` ([#16462](https://github.com/Lightning-AI/lightning/pull/16462))`

**Comment by jgrss** [comment]
Yeah, can you test it with `pytorch_lightning==1.7.7`?

**Comment by mmann1123** [comment]
ok

**Comment by mmann1123** [comment]
Getting these errors for 1.7.7 (had to use cpu)
```
cultionet train --project-path .                 --val-frac 0.2                 --random-seed 500                 --batch-size 4                 --epochs 30                 --filters 32                 --device cpu                 --patience 5                 --learning-rate 0.001                 --reset-model
Global seed set to 500
Processing...
Done!
Global seed set to 500
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ckpt/lightning_logs
Traceback (most recent call last):
  File "/root/.local/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1398, in main
    train_model(args)
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1243, in train_model
    cultionet.fit(
  File "/root/.local/lib/python3.8/site-packages/cultionet/model.py", line 427, in fit
    trainer.fit(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1147, in _run
    self.strategy.setup(self)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/single_device.py", line 74, in setup
    super().setup(trainer)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py", line 153, in setup
    self.setup_optimizers(trainer)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py", line 141, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs, self.optimizer_frequencies = _init_optimizers_and_lr_schedulers(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/optimizer.py", line 194, in _init_optimizers_and_lr_schedulers
    _validate_scheduler_api(lr_scheduler_configs, model)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/core/optimizer.py", line 351, in _validate_scheduler_api
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: The provided lr scheduler `CosineAnnealingLR` doesn't follow PyTorch's LRScheduler API. You should override the `LightningModule.lr_scheduler_step` hook with your own logic if you are using a custom LR scheduler.
```

**Comment by mmann1123** [comment]
1.9.5  appears to be sort of working but only via cpu for me.  Any thoughts on why lighting 1.9.5 would break gpu support?  Different nvidia drivers? 

```
cultionet train --project-path .                 --val-frac 0.2                 --random-seed 500                 --batch-size 4                 --epochs 30                 --filters 32                 --device cpu                 --patience 5                 --learning-rate 0.001                 --reset-model
Global seed set to 500
Processing...
Done!
Global seed set to 500
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ckpt/lightning_logs

   | Name                  | Type              | Params
-------------------------------------------------------------
0  | sigmoid               | Sigmoid           | 0     
1  | cultionet_ResUNet3Psi | CultioNet         | 40.5 M
2  | dist_loss             | TanimotoDistLoss  | 0     
3  | edge_loss             | TanimotoDistLoss  | 0     
4  | crop_loss             | TanimotoDistLoss  | 0     
5  | crop_star_l2_loss     | TanimotoDistLoss  | 0     
6  | crop_star_loss        | TanimotoDistLoss  | 0     
7  | dist_mae              | MeanAbsoluteError | 0     
8  | dist_mse              | MeanSquaredError  | 0     
9  | edge_f1               | F1Score           | 0     
10 | crop_f1               | F1Score           | 0     
11 | edge_mcc              | MatthewsCorrCoef  | 0     
12 | crop_mcc              | MatthewsCorrCoef  | 0     
13 | edge_dice             | Dice              | 0     
14 | crop_dice             | Dice              | 0     
15 | edge_jaccard          | JaccardIndex      | 0     
16 | crop_jaccard          | JaccardIndex      | 0     
-------------------------------------------------------------
40.5 M    Trainable params
0         Non-trainable params
40.5 M    Total params
161.940   Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|               
```

**Comment by mmann1123** [comment]
UPDATE: Nope....  After a bit more waiting, getting the following.    @jgrss 

```
cultionet train --project-path .                 --val-frac 0.2                 --random-seed 500                 --batch-size 4                 --epochs 30                 --filters 32                 --device cpu                 --patience 5                 --learning-rate 0.001                 --reset-model
Global seed set to 500
Processing...
Done!
Global seed set to 500
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: ckpt/lightning_logs

   | Name                  | Type              | Params
-------------------------------------------------------------
0  | sigmoid               | Sigmoid           | 0     
1  | cultionet_ResUNet3Psi | CultioNet         | 40.5 M
2  | dist_loss             | TanimotoDistLoss  | 0     
3  | edge_loss             | TanimotoDistLoss  | 0     
4  | crop_loss             | TanimotoDistLoss  | 0     
5  | crop_star_l2_loss     | TanimotoDistLoss  | 0     
6  | crop_star_loss        | TanimotoDistLoss  | 0     
7  | dist_mae              | MeanAbsoluteError | 0     
8  | dist_mse              | MeanSquaredError  | 0     
9  | edge_f1               | F1Score           | 0     
10 | crop_f1               | F1Score           | 0     
11 | edge_mcc              | MatthewsCorrCoef  | 0     
12 | crop_mcc              | MatthewsCorrCoef  | 0     
13 | edge_dice             | Dice              | 0     
14 | crop_dice             | Dice              | 0     
15 | edge_jaccard          | JaccardIndex      | 0     
16 | crop_jaccard          | JaccardIndex      | 0     
-------------------------------------------------------------
40.5 M    Trainable params
0         Non-trainable params
40.5 M    Total params
161.940   Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                                       | 0/2 [00:00<?, ?it/sTraceback (most recent call last):
  File "/root/.local/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1398, in main
    train_model(args)
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1243, in train_model
    cultionet.fit(
  File "/root/.local/lib/python3.8/site-packages/cultionet/model.py", line 427, in fit
    trainer.fit(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 813, in validation_step
    eval_metrics = self._shared_eval_step(batch, batch_idx)
  File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 743, in _shared_eval_step
    loss = self.calc_loss(batch, predictions)
  File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 634, in calc_loss
    crop_star_l2_loss = self.crop_star_l2_loss(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/cultionet/losses/losses.py", line 373, in forward
    loss = tanimoto_loss(inputs, targets)
  File "/root/.local/lib/python3.8/site-packages/cultionet/losses/losses.py", line 364, in tanimoto_loss
    tpl = (yhat * y).sum(dim=0)
RuntimeError: The size of tensor a (38416) must match the size of tensor b (38221) at non-singleton dimension 0
```

**Comment by jgrss** [comment]
It may be related to the `torch` version. I think you are ahead of what I've been testing and using and the error stems from the PyTorch learning rate scheduler.

I'll get back to you with the `torch` version that's worked for me.

**Comment by jgrss** [comment]
The latest error is caused by one of your .pt files having different dimensions than the rest of the dataset. I'll get back shortly with command line arguments you can add to have cultionet check dimensions.

**Comment by jgrss** [comment]
> It may be related to the `torch` version. I think you are ahead of what I've been testing and using and the error stems from the PyTorch learning rate scheduler.
> 
> I'll get back to you with the `torch` version that's worked for me.

This is regarding the first error with the learning rate scheduler.

**Comment by jgrss** [comment]
> UPDATE: Nope.... After a bit more waiting, getting the following. @jgrss
> 
> ```
> cultionet train --project-path .                 --val-frac 0.2                 --random-seed 500                 --batch-size 4                 --epochs 30                 --filters 32                 --device cpu                 --patience 5                 --learning-rate 0.001                 --reset-model
> Global seed set to 500
> Processing...
> Done!
> Global seed set to 500
> Using bfloat16 Automatic Mixed Precision (AMP)
> GPU available: False, used: False
> TPU available: False, using: 0 TPU cores
> IPU available: False, using: 0 IPUs
> HPU available: False, using: 0 HPUs
> Missing logger folder: ckpt/lightning_logs
> 
>    | Name                  | Type              | Params
> -------------------------------------------------------------
> 0  | sigmoid               | Sigmoid           | 0     
> 1  | cultionet_ResUNet3Psi | CultioNet         | 40.5 M
> 2  | dist_loss             | TanimotoDistLoss  | 0     
> 3  | edge_loss             | TanimotoDistLoss  | 0     
> 4  | crop_loss             | TanimotoDistLoss  | 0     
> 5  | crop_star_l2_loss     | TanimotoDistLoss  | 0     
> 6  | crop_star_loss        | TanimotoDistLoss  | 0     
> 7  | dist_mae              | MeanAbsoluteError | 0     
> 8  | dist_mse              | MeanSquaredError  | 0     
> 9  | edge_f1               | F1Score           | 0     
> 10 | crop_f1               | F1Score           | 0     
> 11 | edge_mcc              | MatthewsCorrCoef  | 0     
> 12 | crop_mcc              | MatthewsCorrCoef  | 0     
> 13 | edge_dice             | Dice              | 0     
> 14 | crop_dice             | Dice              | 0     
> 15 | edge_jaccard          | JaccardIndex      | 0     
> 16 | crop_jaccard          | JaccardIndex      | 0     
> -------------------------------------------------------------
> 40.5 M    Trainable params
> 0         Non-trainable params
> 40.5 M    Total params
> 161.940   Total estimated model params size (MB)
> Sanity Checking DataLoader 0:   0%|                                                                                       | 0/2 [00:00<?, ?it/sTraceback (most recent call last):
>   File "/root/.local/bin/cultionet", line 8, in <module>
>     sys.exit(main())
>   File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1398, in main
>     train_model(args)
>   File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1243, in train_model
>     cultionet.fit(
>   File "/root/.local/lib/python3.8/site-packages/cultionet/model.py", line 427, in fit
>     trainer.fit(
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
>     call._call_and_handle_interrupt(
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
>     return trainer_fn(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
>     self._run(model, ckpt_path=self.ckpt_path)
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
>     results = self._run_stage()
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
>     self._run_train()
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
>     self._run_sanity_check()
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
>     val_loop.run()
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
>     self.advance(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
>     dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
>     self.advance(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
>     output = self._evaluation_step(**kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
>     output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
>     output = fn(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
>     return self.model.validation_step(*args, **kwargs)
>   File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 813, in validation_step
>     eval_metrics = self._shared_eval_step(batch, batch_idx)
>   File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 743, in _shared_eval_step
>     loss = self.calc_loss(batch, predictions)
>   File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 634, in calc_loss
>     crop_star_l2_loss = self.crop_star_l2_loss(
>   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/root/.local/lib/python3.8/site-packages/cultionet/losses/losses.py", line 373, in forward
>     loss = tanimoto_loss(inputs, targets)
>   File "/root/.local/lib/python3.8/site-packages/cultionet/losses/losses.py", line 364, in tanimoto_loss
>     tpl = (yhat * y).sum(dim=0)
> RuntimeError: The size of tensor a (38416) must match the size of tensor b (38221) at non-singleton dimension 0
> ```

From `cultionet train -h` you can use `--expected-dim`, `--expected-height`, and `--expected-width` along with `--delete-mismatches` to check .pt dataset dimensions and delete any ids that do not match what you expect. Be sure to only run with these arguments once in order to avoid calculating this each time. E.g., if you have quarterly data with 100x100 pixel grids...
```commandline
cutltionet train --expected-dim 4 --expected-height 100 --expected-width 100 --delete-mismatches --recalc-zscores
```

**Comment by mmann1123** [comment]
Ok thanks. What is `expected-dim`?

**Comment by mmann1123** [comment]
not sure if it will be helpful but I am pushing to dockerhub the different versions 
docker pull mmann1123/cultionet_195  is lightning 1.9.5, also creating the other versions 
docker pull mmann1123/cultionet_201
docker pull mmann1123/cultionet_177

**Comment by jgrss** [comment]
> Ok thanks. What is `expected-dim`?

This will be the time dimensions.

**Comment by mmann1123** [comment]
gotcha.  

I am also realizing my image shards are alternating between 99x100 and 100x100. Assuming that is problematic.  Regardless. Its crazy late. Heading to bed.

**Comment by jgrss** [comment]
> 



> gotcha.
> 
> I am also realizing my image shards are alternating between 99x100 and 100x100. Assuming that is problematic. Regardless. Its crazy late. Heading to bed. Thanks for your help.

Ha, okay. Yeah, the images need to be identical in time, height, and width. If the `--grid-size` isn't working when you create the data, there might be a bug. You can try the latest from [this branch](https://github.com/jgrss/cultionet/tree/jgrss/issue_63). I added a `rasterio` transform bounds check that should force the height/width when you use `--grid-size`. **Note that I haven't tested this yet, though.**

**Comment by mmann1123** [comment]
Sorry the saga continues @jgrss 

I updated the image shard bounds so each image is now 100x100 (all passed an assertion test to confirm)

with the pytorch-lightning==1.95 docker build:

```
root@813f312d27d3:/home/field_bounds# cultionet create \
>         --transforms {fliplr,flipud,rot90,rot180,rot270,tswarp,tsnoise,tsdrift,roll,gaussian,saltpepper,speckle} \
>         --res 0.00008983152841195214829 \
>         --project-path . \
>         --config-file config.yml \
>         --crop-column class \
>         --grid-size 100 100 \
>         --max-crop-class 1 \
>         --image-date-format %Y%j \
>         --feature-pattern {region}/{image_vi} \
>         --start-date 05-01 \
>         --end-date 05-01

000025_2022 stored.: : 50it [00:58,  1.17s/it]  
```
Creates the transforms in `data/train/processed`, I think as expected.

For training the first time I tried without coarsing the shape and dim:

```
cultionet train --project-path . \
>                 --recalc-zscores\
>                 --val-frac 0.2 \
>                 --random-seed 500 \
>                 --batch-size 4 \
>                 --epochs 30 \
>                 --filters 32 \
>                 --device cpu \
>                 --patience 5 \
>                 --learning-rate 0.001 \
>                 --reset-model
Global seed set to 500
Processing...
Done!
Global seed set to 500
Calculating means: 100%|███████████████████████████████████████████████████████████████████████| 60/60 [00:00<00:00, 74.59it/s]
Calculating SSEs: 100%|████████████████████████████████████████████████████████████████████████| 60/60 [00:00<00:00, 75.09it/s]
Processing...
Done!
Global seed set to 500
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

   | Name                  | Type              | Params
-------------------------------------------------------------
0  | sigmoid               | Sigmoid           | 0     
1  | cultionet_ResUNet3Psi | CultioNet         | 40.5 M
2  | dist_loss             | TanimotoDistLoss  | 0     
3  | edge_loss             | TanimotoDistLoss  | 0     
4  | crop_loss             | TanimotoDistLoss  | 0     
5  | crop_star_l2_loss     | TanimotoDistLoss  | 0     
6  | crop_star_loss        | TanimotoDistLoss  | 0     
7  | dist_mae              | MeanAbsoluteError | 0     
8  | dist_mse              | MeanSquaredError  | 0     
9  | edge_f1               | F1Score           | 0     
10 | crop_f1               | F1Score           | 0     
11 | edge_mcc              | MatthewsCorrCoef  | 0     
12 | crop_mcc              | MatthewsCorrCoef  | 0     
13 | edge_dice             | Dice              | 0     
14 | crop_dice             | Dice              | 0     
15 | edge_jaccard          | JaccardIndex      | 0     
16 | crop_jaccard          | JaccardIndex      | 0     
-------------------------------------------------------------
40.5 M    Trainable params
0         Non-trainable params
40.5 M    Total params
161.940   Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                      | 0/2Traceback (most recent call last):
  File "/root/.local/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1398, in main
    train_model(args)
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1243, in train_model
    cultionet.fit(
  File "/root/.local/lib/python3.8/site-packages/cultionet/model.py", line 427, in fit
    trainer.fit(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 813, in validation_step
    eval_metrics = self._shared_eval_step(batch, batch_idx)
  File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 743, in _shared_eval_step
    loss = self.calc_loss(batch, predictions)
  File "/root/.local/lib/python3.8/site-packages/cultionet/models/lightning.py", line 634, in calc_loss
    crop_star_l2_loss = self.crop_star_l2_loss(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/cultionet/losses/losses.py", line 373, in forward
    loss = tanimoto_loss(inputs, targets)
  File "/root/.local/lib/python3.8/site-packages/cultionet/losses/losses.py", line 364, in tanimoto_loss
    tpl = (yhat * y).sum(dim=0)
RuntimeError: The size of tensor a (40000) must match the size of tensor b (39900) at non-singleton dimension 0
```

Then with adding shape dim and delete-mismatch:

```
cultionet train --project-path . \
>                 --expected-dim 4 \
>                 --expected-height 100 \
>                 --expected-width 100 \
>                 --delete-mismatches \
>                 --recalc-zscores\
>                 --val-frac 0.2 \
>                 --random-seed 500 \
>                 --batch-size 4 \
>                 --epochs 30 \
>                 --filters 32 \
>                 --device cpu \
>                 --patience 5 \
>                 --learning-rate 0.001 \
>                 --reset-model

Global seed set to 500
Processing...
Done!
Global seed set to 500
Checking dimensions: 100%|██████████████████████████████████████████████████████████████████| 300/300 [00:02<00:00, 107.59it/s]
2023-04-14:03:44:27 [WARNING] [cultionet.data.datasets.py:357] 000016_2022_000016_speckle,000009_2022_000009_tsdrift,000015_2022_000015_fliplr,000001_2022_000001_gaussian,000016_2022_000016_tsnoise,000004_2022_000004_rotate-90,000007_2022_000007_rotate-180,000003_2022_000003_rotate-2...
...
...
...
180,000024_2022_000024_roll,000019_2022_000019_s&p,000023_2022_000023_gaussian,000019_2022_000019_roll,000016_2022_000016_roll,000015_2022_000015_tsnoise,000018_2022_000018_tsdrift,000011_2022_000011_rotate-270,000011_2022_000011_gaussian,000015_2022_000015_rotate-180,000008_2022_000008_tsdrift
2023-04-14:03:44:27 [WARNING] [cultionet.data.datasets.py:358] 300 ids did not match the reference dimensions.
2023-04-14:03:44:27 [WARNING] [cultionet.data.datasets.py:363] Removing 300 .pt files.
2023-04-14:03:44:27 [ERROR] [cultionet.data.datasets.py:139] No .pt files were found with pattern data*.pt.
NoneType: None
Processing...
Done!
Global seed set to 500
Traceback (most recent call last):
  File "/root/.local/bin/cultionet", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1398, in main
    train_model(args)
  File "/root/.local/lib/python3.8/site-packages/cultionet/scripts/cultionet.py", line 1175, in train_model
    data_values = get_norm_values(
  File "/root/.local/lib/python3.8/site-packages/cultionet/utils/normalize.py", line 163, in get_norm_values
    ) for batch in data_module.train_dataloader()
  File "/root/.local/lib/python3.8/site-packages/cultionet/data/modules.py", line 37, in train_dataloader
    return DataLoader(
  File "/usr/local/lib/python3.8/dist-packages/torch_geometric/loader/dataloader.py", line 79, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 351, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

```

Does it matter that I have all my data in `espg:4326`?  Which is know can be problematic...  Something else??

Here's an example:
```
with gw.open('time_series_vars/000001/evi/2021091.tif') as src:
...    print(src)
... 
<xarray.DataArray (band: 1, y: 100, x: 100)>
dask.array<open_rasterio-fb3113194509f6bc53eb259dadbe60c9<this-array>, shape=(1, 100, 100), dtype=float64, chunksize=(1, 100, 100), chunktype=numpy.ndarray>
Coordinates:
  * band     (band) int64 1
  * x        (x) float64 36.34 36.34 36.34 36.34 ... 36.35 36.35 36.35 36.35
  * y        (y) float64 -5.449 -5.449 -5.449 -5.449 ... -5.458 -5.458 -5.458
Attributes: (12/13)
    transform:           (8.983152841195215e-05, 0.0, 36.34345918228449, 0.0,...
    crs:                 4326
    res:                 (8.983152841195215e-05, 8.983152841195215e-05)
    is_tiled:            1
    nodatavals:          (nan,)
    _FillValue:          nan
    ...                  ...
    offsets:             (0.0,)
    AREA_OR_POINT:       Area
    filename:            time_series_vars/000001/evi/2021091.tif
    resampling:          nearest
    _data_are_separate:  0
    _data_are_stacked:   0
```

**Comment by jgrss** [comment]
It looks like most, or all, of your .pt files are removed because they don't have the correct dimensions. Can you link to your .pt dataset as well as the new raster time series that you created?

Re: lat/lon, I would probably work in a projection.

**Comment by mmann1123** [comment]
Sorry what do you mean by "link to your .pt dataset as well as the new raster time series that you created"

**Comment by jgrss** [comment]
> Sorry what do you mean by "link to your .pt dataset as well as the new raster time series that you created"
> 

A link where I can download the data.

**Comment by jgrss** [comment]
Hi @mmann1123, 

The height/width dimensions look fine. The issue is the temporal dimension. You have 4 dates per site. However, you set your start/end date from 1 May to 1 May, which cuts off your first date (i.e., Julian day 91). [This DataFrame](https://github.com/jgrss/cultionet/blob/28994cdc060c27ca2231a592be846b71942021af/src/cultionet/utils/model_preprocessing.py#L70) has all 4 dates but Julian day 91 is sliced off [here](https://github.com/jgrss/cultionet/blob/28994cdc060c27ca2231a592be846b71942021af/src/cultionet/utils/model_preprocessing.py#L76-L78).

Previously, I had also added an error trying to fix the bounds when we thought the issue was the height/width dimensions. The latest version of the [`jgrss/issue_63`](https://github.com/jgrss/cultionet/tree/jgrss/issue_63) branch has the fix.

With the fix in `jgrss/issue_63` and running the CLI commands below, the training kicks off as expected. 

```commandline
cultionet create \
        --project-path . \
        --config-file config.yml \
        --crop-column class \
        --grid-size 100 100 \
        --max-crop-class 1 \
        --image-date-format %Y%j \
        --feature-pattern {region}/{image_vi} \
        --start-date 04-01 \
        --end-date 04-01 \
        --transforms none fliplr flipud rot90 rot180 rot270 tswarp tsnoise gaussian saltpepper speckle
```

```commandline
cultionet train \
        --project-path . \
        --expected-dim 4 \
        --expected-height 100 \
        --expected-width 100 \
        --delete-mismatches \
        --recalc-zscores \
        --val-frac 0.2 \
        --random-seed 500 \
        --batch-size 4 \
        --epochs 2 \
        --filters 16 \
        --device cpu \
        --patience 5 \
        --learning-rate 0.001 \
        --reset-model
```
